@startuml

[*] --> トップ
トップ : ログイン
トップ : 会員登録
トップ : キーワード検索
トップ : コンサルティング
トップ : トーク一覧
トップ : 依頼受付一覧
トップ : マイページ
トップ : コンサルタントA
トップ : コンサルタントB
トップ : コンサルタントC
トップ --> ログイン
トップ --> 会員登録
トップ --> キーワード検索結果
トップ --> コンサルティング
トップ --> トーク一覧
トップ --> マイページ
トップ --> コンサルタントA詳細

ログイン : ログイン
ログイン : ゲストログイン

会員登録 : 会員登録してログイン

キーワード検索結果: コンサルタントA
キーワード検索結果: コンサルタントB
キーワード検索結果: コンサルタントC
キーワード検索結果 --> コンサルタントA詳細

コンサルタントA詳細 : リクエストを送る
コンサルタントA詳細 --> リクエスト送信

リクエスト送信 : 送信する

コンサルティング : コンサルタント登録
コンサルティング : コンサルタントを辞める
コンサルティング : 依頼受付一覧
コンサルティング --> コンサルタント登録
コンサルティング --> 依頼受付一覧

コンサルタント登録 : 登録する 

トーク一覧 :トークルーム
トーク一覧 --> トークルーム

トークルーム : メッセージを送信
トークルーム : 取引完了を依頼(依頼者のみ)
トークルーム : 取引完了を受理(コンサルタントのみ)

依頼受付一覧 : 依頼詳細
依頼受付一覧 --> 依頼詳細

依頼詳細 : 依頼を受ける
依頼詳細 : 依頼を拒否する


マイページ : プロフィール編集
マイページ : アカウントの削除



@enduml
