@startuml

[*] --> トップ
トップ : ログイン
トップ : ログアウト
トップ : 会員登録
トップ : マイページ
トップ : キーワード検索
トップ : トーク一覧
トップ : コンサルティング
トップ : ――――――――
トップ : コンサルタントA
トップ : コンサルタントB
トップ : コンサルタントC
トップ --> ログイン
トップ --> 会員登録
トップ --> マイページ
トップ --> キーワード検索結果
トップ --> トーク一覧
トップ --> コンサルティング
トップ --> コンサルタントA詳細

ログイン : ログイン
ログイン : ゲストログイン

会員登録 : 登録する

マイページ : プロフィール編集
マイページ : ログアウト
マイページ : アカウントの削除

キーワード検索結果: コンサルタントA
キーワード検索結果: コンサルタントB
キーワード検索結果: コンサルタントC
キーワード検索結果 --> コンサルタントA詳細

コンサルタントA詳細 : リクエストを送る
コンサルタントA詳細 --> リクエスト送信

リクエスト送信 : 送信する

コンサルティング : コンサルタント登録
コンサルティング : コンサルタントを辞める
コンサルティング : 依頼受付一覧
コンサルティング --> コンサルタント登録
コンサルティング --> 依頼受付一覧


コンサルタント登録 : 登録する 

トーク一覧 :トークルームA
トーク一覧 :トークルームB
トーク一覧 :トークルームC
トーク一覧 --> トークルームA

トークルームA : メッセージを送信
トークルームA : 取引完了を依頼(依頼者のみ)
トークルームA : 取引完了を受理(コンサルタントのみ)

依頼受付一覧 : 依頼詳細A
依頼受付一覧 : 依頼詳細B
依頼受付一覧 : 依頼詳細C
依頼受付一覧 --> 依頼詳細A

依頼詳細A : 依頼を受ける
依頼詳細A : 依頼を拒否する

@enduml
